###################################################################
#                                                                 #
#          Configuration file climate data pipeline               #
#                                                                 #
###################################################################
directories:
  existing_input: /gpfs/projects/meteo/DATA/FAO/RODRI_copy/ERA5/0.25/t2m/ #Datos de entrada
  homogenization: /gpfs/projects/meteo/DATA/FAO/homogenization #Salida
  temporal: /gpfs/projects/meteo/DATA/FAO/temporal_files #Temporal

requests:
- identifier: t_daily_ERA5_FAO #Nombre para el calculo
  STAGES:
  - homogenization #Que etapa del calculo lanzas
  project: 
    name: ERA5 #nombre del proyecto
    type: observations #si es observacion o proyeccion 
    format: gridded #si es gridded o point
  configuration:
    variables:
    - tas #la variable que queires calcular
    temporalResolution: daily #resolucion temporal a la que quierres la salida
    domain: None #no 
    filter_paths: true  #filtro de los ficheros donde busca el proyect, type, format
    id: reanalysis-era5-single-levels #el nombre que sale en el cds cuando lo descargas
    variable_mapping: /gpfs/users/chantreuxa/FAO/scripts/homogenization/rodrigo_era5_variable_config.yml
    timeCoverage:
      start: 1940-01-01
      end: 2022-12-31
    source: CDS #existing input de rodri
    area:
      name: Global
      coords:
        - -90
        - -180
        - 90
        - 180

