###################################################################
#                                                                 #
#          Configuration file climate data pipeline               #
#                                                                 #
###################################################################

directories:
  existing_input: /gpfs/projects/meteo/DATA/FAO/input_placeholder
  homogenization: /gpfs/projects/meteo/DATA/FAO/homogenization
  temporal: /gpfs/projects/meteo/DATA/FAO/temporal_files
  interpolation: /gpfs/projects/meteo/DATA/FAO/interpolation
  biasadjustment: /gpfs/projects/meteo/DATA/FAO/biasadjustment
  indices: /gpfs/projects/meteo/DATA/FAO/final_products/indices

requests:
- identifier: CERRA-land_all_placeholder
  STAGES:
  - all
  project:
    name: CERRA-land
    type: observations
    format: gridded
  configuration:
    variables:
    - tas
    temporalResolution: daily
    orig_temporalResolution: None
    level: surface
    domain: None
    id: reanalysis-cerra-land
    source: CDS
    filter_paths: True
    timeCoverage:
      start: 1980-01-01
      end: 2022-12-31
    area:
      name: Global
      coords:
        - -90
        - -180
        - 90
        - 180

  interpolation:
    grid_type:
      custom_grid: None
      grid_path: /gpfs/users/chantreuxa/FAO/fao-scripts/tools/grid_era
    method: conservative_normed

  indices:
    - name: placeholder-index
      params:
        temporal_aggregation:
          - MS
        chunksize:
          x: 60
          y: 60

