directories:
  input: /lustre/gmeteo/WORK/PROYECTOS/2022_C3S_Atlas/workflow/datasets/CICAv2.0_refactored/compressed_v2/c3s-atlas-dataset/
  temporary: /lustre/gmeteo/WORK/PROYECTOS/2022_C3S_Atlas/workflow/products/CICAv2/v20231017/c3s-atlas-dataset_v2_old_vars/temporal_products/var_replace/main_replace/set_replace
  output: /lustre/gmeteo/WORK/PROYECTOS/2022_C3S_Atlas/workflow/products/CICAv2/v20231017/c3s-atlas-dataset_v2_old_vars/
  validation: /lustre/gmeteo/WORK/PROYECTOS/2022_C3S_Atlas/workflow/products/CICAv2/v20231017/c3s-atlas-dataset_v2_old_vars/validation/

data:
- type: data_type_replace
  project: project_replace
  spatial_mask: spatial_mask_replace
  scenario: scenario_replace
  period: period_replace #1940-2022
  variable:
  - var_replace
  members_subset:
    - "CCCma_CanESM2_r1i1p1"
    - "CCCma_CanESM2_r2i1p1"
    - "CNRM-CERFACS_CNRM-CM5_r1i1p1"
    - "ICHEC_EC-EARTH_r12i1p1"
    - "ICHEC_EC-EARTH_r14i1p1"
    - "IPSL_IPSL-CM5A-MR_r1i1p1"
    - "MOHC_HadGEM2-ES_r1i1p1"
    - "MOHC_HadGEM2-ES_r2i1p1"
    - "MPI-M_MPI-ESM-LR_r1i1p1"
    - "MPI-M_MPI-ESM-LR_r2i1p1"
    - "MPI-M_MPI-ESM-LR_r3i1p1"
    - "MPI-M_MPI-ESM-MR_r1i1p1"
    - "NCC_NorESM1-M_r1i1p1"
    - "BCC_bcc-csm1-1-m_r1i1p1"
    - "BCC_bcc-csm1-1_r1i1p1"
    - "CCCma_CanCM4_r1i1p1"
    - "CMCC_CMCC-CESM_r1i1p1"
    - "CMCC_CMCC-CMS_r1i1p1"
    - "CMCC_CMCC-CM_r1i1p1"
    - "CSIRO-BOM_ACCESS1-0_r1i1p1"
    - "CSIRO-BOM_ACCESS1-3_r1i1p1"
    - "CSIRO-QCCCE_CSIRO-Mk3-6-0_r1i1p1"
    - "LASG-CESS_FGOALS-g2_r1i1p1"
    - "MOHC_HadCM3_r1i1p1"
    - "MOHC_HadGEM2-CC_r1i1p1"
    - "NASA-GISS_GISS-E2-R_r6i1p1"
    - "NCAR_CCSM4_r1i1p1"
    - "NOAA GFDL_GFDL-CM3_r1i1p1"
    - "NOAA GFDL_GFDL-ESM2G_r1i1p1"
    - "NOAA GFDL_GFDL-ESM2M_r1i1p1"
    - "NSF-DOE-NCAR_CESM1-BGC_r1i1p1"
    - "NSF-DOE-NCAR_CESM1-CAM5_r1i1p1"
  source: local_machine

products:
  temporal_series-user:
    variable: var_replace
    scenarios:
      main: main_replace
      baseline: baseline_replace
      fill_baseline: fill_baseline_replace
    magnitudes:
      raw: true
      anom: true
      relanom: relanom_replace
    periods: period_climatology_replace
    baselines:
      preIndustrial: 1850-1900
      AR5: 1986-2005
      AR6: 1995-2014
      WMO1: 1961-1990
      WMO2: 1981-2010
      WMO3: 1991-2020
    time_filters: time_filters_replace
    time_aggregation_stat: aggregation_replace
    region_aggregation:
      mask_file: mask_replace
      set: set_replace
    chunknum: 3
