directories:
  input: /lustre/gmeteo/WORK/PROYECTOS/2022_C3S_Atlas/workflow/datasets/CICAv2.0_refactored/compressed_v2/c3s-atlas-dataset/
  temporary: /lustre/gmeteo/WORK/PROYECTOS/2022_C3S_Atlas/workflow/products/CICAv2/v20231017/c3s-atlas-dataset_v2_old_vars/temporal_products/var_replace/main_replace
  output: /lustre/gmeteo/WORK/PROYECTOS/2022_C3S_Atlas/workflow/products/CICAv2/v20231017/c3s-atlas-dataset_v2_old_vars/
  validation: /lustre/gmeteo/WORK/PROYECTOS/2022_C3S_Atlas/workflow/products/CICAv2/v20231017/c3s-atlas-dataset_v2_old_vars/validation/

data:
- type: data_type_replace
  project: project_replace
  scenario: scenario_replace
  period: period_replace #1940-2022
  variable:
  - var_replace
  source: local_machine

products:
  trends-user:
    variable: var_replace
    scenarios:
      main: main_replace
      baseline: baseline_replace
      fill_baseline: fill_baseline_replace
    magnitudes:
      trend: true
      trend_consensus: false
    periods:
      SHORT-TERM: 1991-2020
      LONG-TERM: 1950-2020
    warming_levels: None
    baselines: None
    time_filters:
      Annual: 01-12
      DecFeb: 12-02
      MarMay: 03-05
      JunAug: 06-08
      SepNov: 09-11
      Jan: 01-01
      Feb: 02-02
      Mar: 03-03
      Apr: 04-04
      May: 05-05
      Jun: 06-06
      Jul: 07-07
      Aug: 08-08
      Sep: 09-09
      Oct: 10-10
      Nov: 11-11
      Dec: 12-12
    time_aggregation_stat: mean
    region_aggregation:
      mask_file: None
      set: None
    chunksize:
      lat: 90
      lon: 180
