directories:
  input: /lustre/gmeteo/WORK/PROYECTOS/2022_C3S_Atlas/workflow/datasets/CICAv2.0_refactored/compressed_v2/c3s-atlas-dataset/
  temporary: /lustre/gmeteo/WORK/PROYECTOS/2022_C3S_Atlas/workflow/products/CICAv2/v20231017/c3s-atlas-dataset_v2_old_vars/temporal_products/var_replace/main_replace
  output: /lustre/gmeteo/WORK/PROYECTOS/2022_C3S_Atlas/workflow/products/CICAv2/v20231017/c3s-atlas-dataset_v2_old_vars/
  validation: /lustre/gmeteo/WORK/PROYECTOS/2022_C3S_Atlas/workflow/products/CICAv2/v20231017/c3s-atlas-dataset_v2_old_vars/validation/

data:
- type: data_type_replace
  project: project_replace
  spatial_mask: spatial_mask_replace
  members_subset: None
  scenario: scenario_replace
  period: period_replace #1940-2022
  variable:
  - var_replace
  source: local_machine

products:
  climatology-user:
    variable: var_replace
    scenarios:
      main: main_replace
      baseline: baseline_replace
      fill_baseline: fill_baseline_replace
    magnitudes:
      raw: true
      anom: true
      relanom: relanom_replace
      anom_agreement: anom_consensus_replace
      anom_emergence: anom_robustness_replace
    periods: period_climatology_replace
    warming_levels:
      levels: levels_replace
      file: /lustre/gmeteo/WORK/chantreuxa/cica/Products/products/resources/resources/warming_levels/CMIP5_WarmingLevels.csv
    baselines:
      AR5: 1986-2005
      AR6: 1995-2014
      WMO2: 1981-2010
      WMO1: 1961-1990
      WMO3: 1991-2020
    time_filters: time_filters_replace
    time_aggregation_stat: aggregation_replace
    region_aggregation:
      mask_file: None
      set: None
    chunksize:
      lat: 60
      lon: 90 
    chunknum: 3
